import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptRouterModule } from '@nativescript/angular';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { AuthGuard } from '@src/app/modules/auth/auth.guard';
import { AuthLayoutComponent } from '@src/app/layouts/auth-layout/auth-layout.component';
import { AppResolverService } from '@src/app/app-resolver.service';
import { HomeComponent } from '@src/app/modules/home/home.component';
import { ContentLayoutComponent } from '@src/app/layouts/content-layout/content-layout.component';

export const routes: Routes = [
  // {
  //   path: '',
  //   component: ContentLayoutComponent,
  //   canActivate: [AuthGuard],
  //   // resolve: {
  //   //   message: AppResolverService,
  //   // },
  //   children: [
  //     {
  //       path: '',
  //       // canActivate: [AuthGuard],
  //       canActivateChild: [AuthGuard],

  //       loadChildren: () =>
  //         import('@src/app/modules/home/home.module').then((m) => m.HomeModule),
  //     },
  //   ],
  // },

  {
    path: '',
    redirectTo: '/content',
    pathMatch: 'full',
  },
  {
    path: 'auth',
    // component: AuthLayoutComponent,
    loadChildren: () =>
      import('@src/app/modules/auth/auth.module').then((m) => m.AuthModule),
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
  {
    path: 'content',
    component: ContentLayoutComponent,
    children: [
      // {
      //   path: '',
      //   redirectTo: '/home',
      //   // pathMatch: 'full',
      // },
      {
        path: 'home',
        // canActivate: [AuthGuard],
        outlet: 'homeTab',
        component: HomeComponent,
        // loadChildren: () =>
        //   import('@src/app/modules/home/home.module').then((m) => m.HomeModule),
      },
    ],
    // canActivate: [AuthGuard],
    // loadChildren: () =>
    //   import('@src/app/layouts/content-layout/content-layout.module').then(
    //     (m) => m.ContentLayoutModule
    //   ),
  },
];

@NgModule({
  imports: [
    NativeScriptRouterModule,
    NativeScriptRouterModule.forRoot(
      routes
      // { enableTracing: true }
    ),
  ],
  exports: [NativeScriptRouterModule],
})
export class AppRoutingModule {}
