import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from '@nativescript/angular';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { AuthLayoutComponent } from '@src/app/layouts/auth-layout/auth-layout.component';
import { AuthGuard } from '@src/app/modules/auth/auth.guard';
import { AppResolverService } from '@src/app/app-resolver.service';
import { ContentLayoutTnsComponent } from '@src/app/layouts/content-layout-tns/content-layout-tns.component';

export const routes: Routes = [
  {
    path: '',
    component: ContentLayoutTnsComponent,
    canActivate: [AuthGuard],
    // resolve: {
    //   message: AppResolverService,
    // },
    children: [
      {
        path: '',
        // canActivate: [AuthGuard],
        canActivateChild: [AuthGuard],

        loadChildren: () =>
          import('@src/app/modules/home/home.module').then((m) => m.HomeModule),
      },
    ],
  },
  {
    path: 'auth',
    // component: AuthLayoutComponent,
    loadChildren: () =>
      import('@src/app/modules/auth/auth.module').then((m) => m.AuthModule),
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
];

@NgModule({
  imports: [NativeScriptRouterModule, NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule],
})
export class AppRoutingModule {}
