import { HttpClient, HttpClientModule } from '@angular/common/http';
import { AngularFireModule } from '@angular/fire/compat';
import { AngularFireAuthModule } from '@angular/fire/compat/auth';
import { AngularFirestoreModule } from '@angular/fire/compat/firestore';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import {
  TranslateModule,
  TranslateCompiler,
  TranslateLoader,
} from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { TranslateMessageFormatCompiler } from 'ngx-translate-messageformat-compiler';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AuthModule } from '@src/app/modules/auth/auth.module';
import { ContentLayoutComponent } from '@src/app/layouts/content-layout/content-layout.component';
import { CoreModule } from '@src/app/core/core.module';
import { PageNotFoundComponent } from '@src/app/shared/components/page-not-found/page-not-found.component';
import { SharedModule } from '@src/app/shared/shared.module';
import { SearchBarComponent } from '@src/app/shared/components/search-bar/search-bar.component';
import { SidemenuComponent } from '@src/app/shared/components/sidemenu/sidemenu.component';
import { SidemenuItemComponent } from '@src/app/shared/components/sidemenu-item/sidemenu-item.component';
import { TestComponent } from '@src/app/shared/components/test/test.component';
import { ToolbarComponent } from '@src/app/shared/components/toolbar/toolbar.component';
import { ToolbarNotificationComponent } from '@src/app/shared/components/toolbar-notification/toolbar-notification.component';
import { UserMenuComponent } from '@src/app/shared/components/user-menu/user-menu.component';
import { AuthLayoutComponent } from '@src/app/layouts/auth-layout/auth-layout.component';
import { LanguagePickerComponent } from '@src/app/shared/components/language-picker/language-picker.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BackendService } from '@src/app/core/services/backend.service';
import { environment } from '../environments/environment';

// required for AOT compilation
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
  // return new TranslateHttpLoader(http);
}

@NgModule({
  declarations: [
    AppComponent,
    ContentLayoutComponent,
    PageNotFoundComponent,
    SearchBarComponent,
    SidemenuComponent,
    SidemenuItemComponent,
    TestComponent,
    ToolbarComponent,
    ToolbarNotificationComponent,
    UserMenuComponent,
    LanguagePickerComponent,
    AuthLayoutComponent,
    AutoGeneratedComponent,
  ],
  imports: [
    BrowserModule,
    RouterModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireAuthModule,
    AngularFirestoreModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient],
      },
      compiler: {
        provide: TranslateCompiler,
        useClass: TranslateMessageFormatCompiler,
      },
      defaultLanguage: 'en',
    }),
    AuthModule,

    // Shared & Core
    CoreModule,
    SharedModule,
  ],

  providers: [BackendService],
  bootstrap: [AppComponent],
})
export class AppModule {}
